language: python
python: 2.7
cache:
  - pip

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - coverage run "$(which pytest)"
  - coverage report -m  && coverage xml
  - flake8 .

after_success:
  - codecov
