language: python
python: 2.7

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.pip
  - pip install pytest pytest-django
script:
  - py.test --ds=skeleton.settings xenserver/
